name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2-beta
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Distribution
      run: npm run build:dist
    - name: Run Tests
      run: npm run test
    - name: Extract New Version
      id: version
      run: |
        NEW_VERSION=$(cat .VERSION) 
        if [ "$(node -e 'console.log(require(`./package.json`).version)')" != "$NEW_VERSION" ]; then
          echo "::set-output name=new::$(echo $NEW_VERSION)"
        fi
    - name: Build docs and add artifacts
      if: steps.version.outputs.new  
      run: |
        npm run build:docs
        npm install --package-lock
        git config --global user.name '(none)' && git config --global user.email 'noreply@github.com' && git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        git add dist
        git add package-lock.json
        git add readme.md
        git commit -n -m "Add dist and readme for $NEW_VERSION" --allow-empty
        git stash save --keep-index --include-untracked
        git stash drop
      env:
        NEW_VERSION: ${{ steps.version.outputs.new }}
    - name: Publish
      if: steps.version.outputs.new  
      env:
        NEW_VERSION: ${{ steps.version.outputs.new }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
        echo "Updating to $NEW_VERSION"
        npm version $NEW_VERSION
        npm publish
        git tag -a $NEW_VERSION -m "v$NEW_VERSION"
        git push
        git push --tags